# Generated by Django 4.2.30 on 2026-09-03 17:14

from django.conf import settings
import django.contrib.auth.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('user_type', models.CharField(choices=[('SEEKER', "Demandeur d'emploi"), ('PROVIDER', "Offreur d'emploi / Entreprise")], max_length=10)),
                ('first_name', models.CharField(help_text="Prénom tel qu'inscrit sur la CNI", max_length=150)),
                ('last_name', models.CharField(help_text="Nom de famille tel qu'inscrit sur la CNI", max_length=150)),
                ('age', models.IntegerField(blank=True, help_text='Âge du candidat', null=True)),
                ('sex', models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('O', 'Autre / Préfère ne pas répondre')], max_length=1)),
                ('cni_number', models.CharField(help_text="Numéro de la CNI (vérifié par l'admin)", max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text="Position GPS de l'utilisateur", null=True, srid=4326)),
                ('is_verified', models.BooleanField(default=False, help_text='Vérifié par email (clic sur le lien)')),
                ('is_admin_verified', models.BooleanField(default=False, help_text='Vérifié manuellement par un admin (après contrôle de la CNI)')),
                ('cni_recto', models.ImageField(blank=True, help_text='Photo recto de la CNI', null=True, upload_to='cni/recto/')),
                ('cni_verso', models.ImageField(blank=True, help_text='Photo verso de la CNI', null=True, upload_to='cni/verso/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(default=list)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('preferred_work_zone', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Zone générée basée sur la localisation et le rayon', null=True, srid=4326)),
                ('max_commute_km', models.IntegerField(default=20, help_text='Rayon maximal de déplacement en km')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('intervention_zone', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Zone générée basée sur la localisation et le rayon', null=True, srid=4326)),
                ('intervention_radius_km', models.IntegerField(default=50, help_text="Rayon d'intervention en km")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
