"""
Django settings for gwork project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from decouple import config
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'corsheaders',
    'django.contrib.staticfiles',
      
    # Activation de GeoDjango (DOIT être avant tes apps)
    'django.contrib.gis',
    
    # Tes applications
    'users.apps.UsersConfig',
  
    # Packages tiers
    'rest_framework',
    'rest_framework_gis',
    'django_filters',
 'drf_spectacular',  
]


MIDDLEWARE = [
     'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'gwork.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gwork.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.contrib.gis.db.backends.postgis', # Moteur PostGIS
#        'NAME': 'gwork_db',
#        'USER': 'gwork_user',
#        'PASSWORD': 'gwork_password',
#        'HOST': 'localhost',
#        'PORT': '5432',
#    }
#}
DATABASES = {
    'default': dj_database_url.parse(
        config('DATABASE_URL'),
        conn_max_age=600,
        engine='django.contrib.gis.db.backends.postgis',
    )
}
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# gwork/settings.py

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
    ,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema' ,   
}
AUTH_USER_MODEL = 'users.User'
# gwork/settings.py

import os


# Configuration des fichiers médias (pour les photos de CNI)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# (Garde ta configuration EMAIL et AUTH_USER_MODEL existantes)
# gwork/settings.py

# Configuration Email (Gmail)
EMAIL_BACKEND =config('EMAIL_BACKEND')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')  # Ton email Gmail
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')  # Mot de passe d'application à 16 caractères
DEFAULT_FROM_EMAIL = f'GWork <{EMAIL_HOST_USER}>'

# URL du frontend (pour les liens dans les emails)
FRONTEND_URL = 'http://localhost:3000'
BACKEND_URL = 'http://localhost:8000'

# Durée de validité des tokens (en secondes)
EMAIL_VERIFICATION_TOKEN_TIMEOUT = 86400  # 24 heures
PASSWORD_RESET_TOKEN_TIMEOUT = 3600  # 1 heure
RISKY_ACTION_TOKEN_TIMEOUT = 900  # 15 minutes
# Configuration Spectacular (personnalisation de la doc)
SPECTACULAR_SETTINGS = {
    'TITLE': 'GWork API',
    'DESCRIPTION': (
        'API de la plateforme GWork : mise en relation B2B/B2C '
        'des demandeurs d\'emploi et des offreurs avec recherche '
        'géospatiale avancée.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,  # Ne pas exposer le schéma brut publiquement
    
    # Configuration de l'authentification dans Swagger
    'COMPONENT_SPLIT_REQUEST': True,
    
    # Tags pour organiser les endpoints dans la doc
    'TAGS': [
        {'name': 'Authentification', 'description': 'Inscription, login, vérification email'},
        {'name': 'Utilisateurs', 'description': 'Gestion des profils utilisateurs'},
        {'name': 'Offres d\'emploi', 'description': 'Création et recherche d\'offres'},
        {'name': 'Candidatures', 'description': 'Gestion des candidatures'},
    ],
    
    # Configuration Swagger UI
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,  # Garde le token JWT après refresh de la page
        'displayOperationId': False,
        'filter': True,  # Barre de recherche des endpoints
    },
}
# Configuration CORS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Ton frontend React
    "http://127.0.0.1:3000",
    "https://gworks.netlify.app",
]

# Si tu veux autoriser les cookies/credentials
CORS_ALLOW_CREDENTIALS = True