# Generated by Django 4.2.30 on 2026-09-03 21:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='intervention_radius_km',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='intervention_zone',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='max_commute_km',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='preferred_work_zone',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='user',
            name='cni_number',
            field=models.CharField(help_text='Numéro de la CNI', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cni_recto',
            field=models.ImageField(blank=True, help_text='Photo recto CNI', null=True, upload_to='cni/recto/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cni_verso',
            field=models.ImageField(blank=True, help_text='Photo verso CNI', null=True, upload_to='cni/verso/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin_verified',
            field=models.BooleanField(default=False, help_text='Vérifié par un admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Vérifié par email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Position GPS', null=True, srid=4326),
        ),
    ]
